CREATE OR REPLACE STREAM "DESTINATION_SQL_STREAM" ("DC_NOME" varchar(30),"CD_ESTACAO" varchar(4), "PRECIPITACAO" real, "TEMP_MAX" real, "TEMP_INST" real,"TEMP_MIN" real,"UMD_INST" real,"HORA" varchar(4));
CREATE OR REPLACE PUMP "STREAM_PUMP" AS INSERT INTO "DESTINATION_SQL_STREAM"
SELECT STREAM DC_NOME, CD_ESTACAO, PRECIPITACAO, TEMP_MAX,TEMP_INST,TEMP_MIN,UMD_INST,HORA
FROM "SOURCE_SQL_STREAM_001";
